modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/SistrScarlet/Transform-Into-LittleMaid/issues"
license = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/blob/1.16_Architectury/LICENCE.md"

[[mods]]
modId = "transformintolittlemaid"
version = "${version}"
displayName = "Transform Into LittleMaid Mod"
authors = "Sistr"
description = "メイドさんに変身するModです"
logoFile = "icon.png"

[[dependencies.transformintolittlemaid]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.66,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "littlemaidmodelloader"
mandatory = true
versionRange = "[2.5.3,)"