modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/SistrScarlet/Transform-Into-LittleMaid/issues"
license = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/blob/1.16_Architectury/LICENCE.md"

[[mods]]
modId = "transformintolittlemaid"
version = "${version}"
displayName = "Transform Into LittleMaid Mod"
authors = "Sistr"
description = "メイドさんに変身するModです"
logoFile = "icon.png"

[[dependencies.transformintolittlemaid]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "architectury"
mandatory = true
versionRange = "[6.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "littlemaidmodelloader"
mandatory = true
versionRange = "[5.1.0,)"
ordering = "AFTER"
side = "BOTH"