modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/blob/1.16_Architectury/LICENCE.md"

[[mods]]
modId = "transformintolittlemaid"
version = "${version}"
displayName = "Transform Into LittleMaid Mod"
authors = "Sistr"
description = '''
メイドさんに変身するModです
'''
#logoFile = ""

[[dependencies.transformintolittlemaid]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.49,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId="littlemaidmodelloader"
mandatory=true
versionRange="[4.0.0,)"
ordering="NONE"
side="BOTH"