modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = ""

[[mods]]
modId = "transformintolittlemaid"
version = "${version}"
displayName = "Transform Into LittleMaid Mod"
authors = "Sistr"
description = '''
メイドさんに変身するModです
'''
#logoFile = ""

[[dependencies.transformintolittlemaid]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transformintolittlemaid]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"